CREATE TABLE [dbo].[Message]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[Title] NVARCHAR(100) NOT NULL,
	[Content] NVARCHAR(4000) NOT NULL,
	[Username] NVARCHAR(50) NOT NULL,
	[SendDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[UpdateDate] DATETIME2 NULL,
	CONSTRAINT PK_Message PRIMARY KEY ([Id])
)
